insert into categoria values(1, 'bronze1', 5);
insert into categoria values(2, 'bronze2', 5.70);
insert into categoria values(3, 'prata1', 6.00);
insert into categoria values(4, 'prata2', 6.70);
insert into categoria values(5, 'ouro1', 7.50);
insert into categoria values(6, 'ouro2', 7.70);
insert into categoria values(7, 'lancam1', 9.00);
insert into categoria values(8, 'lancam2', 9.50);
insert into categoria values(9, 'super lancam1', 10.00);
insert into categoria values(10, 'super lancam2', 10.70);